version: "3.4"

services:
  nginx:
    build:
      dockerfile:  ./docker/nginx.dockerfile
      context: .
    image: nginx:v2
    container_name: nginx_https
    ports:
      - "80:80" 
      - "443:443" 
    networks:
      -  nwresumax
    depends_on:
      -  resumax1
      -  resumax2
      -  resumax3
    restart: always
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
      image: certbot/certbot:latest
      volumes:
       - ./data/certbot/www/:/var/www/certbot/:rw
       - ./data/certbot/conf/:/etc/letsencrypt/:rw  

  pgresumax:
    build:
      dockerfile:  ./docker/pgresumax.dockerfile
      context: .
    image: gustavo/pgresumax:v2
    container_name: pgresumax2
    ports:
      - "5432"
    networks:
      - nwresumax
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
  resumax1:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v2
    container_name: resumax_https1
    ports:
      - "8000"
    networks:
      - nwresumax
    depends_on:
      - pgresumax
  
  resumax2:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v2
    container_name: resumax_https2
    ports:
      -  "8000"
    networks:
      - nwresumax
    depends_on:
      - pgresumax
  
  resumax3:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v2
    container_name: resumax_https3
    ports:
      - "8000"    
    networks:
      - nwresumax
    depends_on:
      - pgresumax

networks:
  nwresumax:
   driver: bridge

volumes:
  pgdata:

