version: "3.4"

services:
  nginx:
    image: nginx:1.15-alpine 
    container_name: nginx_https
    ports:
      - "80:80" 
      - "443:443" 
    networks:
      -  nwresumax
    depends_on:
      -  resumax1
      -  resumax2
      -  resumax3
      -  certbot
    volumes: 
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot 

  certbot: 
    image: certbot/certbot:latest
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot

  pgresumax:
    build:
      dockerfile:  ./docker/pgresumax.dockerfile
      context: .
    image: gustavo/pgresumax:v2
    container_name: pgresumax2
    ports:
      - "5432"
    networks:
      - nwresumax
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
  resumax1:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v2
    container_name: resumax_https1
    ports:
      - "8000"
    networks:
      - nwresumax
    depends_on:
      - pgresumax
  
  resumax2:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v2
    container_name: resumax_https2
    ports:
      -  "8000"
    networks:
      - nwresumax
    depends_on:
      - pgresumax
  
  resumax3:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v2
    container_name: resumax_https3
    ports:
      - "8000"    
    networks:
      - nwresumax
    depends_on:
      - pgresumax

networks:
  nwresumax:
   driver: bridge

volumes:
  pgdata:
