version: "3.4"

services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context:  .
    image: gustavo/nginx_resumax:v1
    container_name: nginx
    ports:
     -  80:80
     -  443:443
    networks:
     -  nwresumax
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
    
    depends_on:
     -  resumax1
     -  resumax2
     -  resumax3

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw

  pgresumax:
    build:
      dockerfile:  ./docker/pgresumax.dockerfile
      context: .
    image: gustavo/pgresumax:v1
    container_name: pgresumax
    ports:
      - "5432"
    networks:
      - nwresumax
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
  resumax1:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v1
    container_name: resumax1
    ports:
      - "8000"
    networks:
      - nwresumax
    depends_on:
      - pgresumax
  
  resumax2:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v1
    container_name: resumax2
    ports:
      -  "8000"
    networks:
      - nwresumax
    depends_on:
      - pgresumax
  
  resumax3:
    build: 
      dockerfile: ./docker/resumax.dockerfile
      context: .
    image: gustavo/resumax:v1
    container_name: resumax3
    ports:
     -  "8000"    
    networks:
      - nwresumax
    depends_on:
      - pgresumax

networks:
  nwresumax:
   driver: bridge

volumes:
  pgdata:
